#docker-compose.yml specification: https://docs.docker.com/compose/compose-file/
version: '3'
services:
  java-web-app-server-1:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8091:8091"