#name: Deploy App to EB
#
#on:
#  push:
#    branches:
#      - master
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - run: docker-compose -f docker-compose.build.yaml up
#
#      - name: Generate deployment package
#        run: zip -r deploy.zip . -x '*.git*'
#
#      - name: Deploy to EB
#        uses: einaregilsson/beanstalk-deploy@v18
#        with:
#          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
#          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
#          application_name: docker-spring-mvc
#          environment_name: Dockerspringmvc-env
#          existing_bucket_name: elasticbeanstalk-eu-central-1-232026826030
#          region: eu-central-1
#          version_label: 12345
#          deployment_package: deploy.zip
